### ISSUE TITLE
Entire site and API is down

### ISSUE THREAD

**Issue by mcohen9** [postageapp/postageapp-ruby#22]
API and website is fully down for 24 hours now.

**Comment by mcohen9** [comment]
Site is down again!!!

**Comment by mcohen9** [comment]
Down again since yesterday!!

**Comment by mcohen9** [comment]
Emails stuck in preparing mode since this morning. Can someone please respond here why this is happening every single month now?

**Comment by mcohen9** [comment]
Past few days response time for API calls is very slow. Requests taking 20 seconds today. This is a very noticeable problem in our application now. Please Help

**Comment by mcohen9** [comment]
Requests are still very slow. Some requests getting error now also. 

Error message:

true is not a symbol nor a string

                              lib/postageapp/failed_request.rb:35:in `block in resend_all'

                              lib/postageapp/failed_request.rb:21:in `foreach'

                              lib/postageapp/failed_request.rb:21:in `resend_all'

                              lib/postageapp/request.rb:64:in `send'
